FROM node:lts-alpine3.19

WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY ./package*.json ./

# Install dependencies
RUN npm install

ENTRYPOINT ["npm", "run", "dev", "--host", "0.0.0.0"]
