// This file is auto-generated by @hey-api/openapi-ts

import { type Options, returnListApiV1HealthTestListGet, generateSvgFromPromptApiV1SvgGenerateFromPromptPost, runRobotUsingSvgApiV1RobotRunWithSvgPost, runRobotUsingImageApiV1RobotRunWithImagePost, summarizeTextApiV1GptsummarizePost } from '../sdk.gen';
import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { ReturnListApiV1HealthTestListGetData, GenerateSvgFromPromptApiV1SvgGenerateFromPromptPostData, GenerateSvgFromPromptApiV1SvgGenerateFromPromptPostError, RunRobotUsingSvgApiV1RobotRunWithSvgPostData, RunRobotUsingSvgApiV1RobotRunWithSvgPostError, RunRobotUsingImageApiV1RobotRunWithImagePostData, RunRobotUsingImageApiV1RobotRunWithImagePostError, SummarizeTextApiV1GptsummarizePostData, SummarizeTextApiV1GptsummarizePostError, SummarizeTextApiV1GptsummarizePostResponse } from '../types.gen';
import type { AxiosError } from 'axios';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: (options?.client ?? _heyApiClient).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const returnListApiV1HealthTestListGetQueryKey = (options: Options<ReturnListApiV1HealthTestListGetData>) => createQueryKey('returnListApiV1HealthTestListGet', options);

export const returnListApiV1HealthTestListGetOptions = (options: Options<ReturnListApiV1HealthTestListGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await returnListApiV1HealthTestListGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: returnListApiV1HealthTestListGetQueryKey(options)
    });
};

export const generateSvgFromPromptApiV1SvgGenerateFromPromptPostQueryKey = (options: Options<GenerateSvgFromPromptApiV1SvgGenerateFromPromptPostData>) => createQueryKey('generateSvgFromPromptApiV1SvgGenerateFromPromptPost', options);

export const generateSvgFromPromptApiV1SvgGenerateFromPromptPostOptions = (options: Options<GenerateSvgFromPromptApiV1SvgGenerateFromPromptPostData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await generateSvgFromPromptApiV1SvgGenerateFromPromptPost({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: generateSvgFromPromptApiV1SvgGenerateFromPromptPostQueryKey(options)
    });
};

export const generateSvgFromPromptApiV1SvgGenerateFromPromptPostMutation = (options?: Partial<Options<GenerateSvgFromPromptApiV1SvgGenerateFromPromptPostData>>) => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<GenerateSvgFromPromptApiV1SvgGenerateFromPromptPostError>, Options<GenerateSvgFromPromptApiV1SvgGenerateFromPromptPostData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await generateSvgFromPromptApiV1SvgGenerateFromPromptPost({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const runRobotUsingSvgApiV1RobotRunWithSvgPostQueryKey = (options: Options<RunRobotUsingSvgApiV1RobotRunWithSvgPostData>) => createQueryKey('runRobotUsingSvgApiV1RobotRunWithSvgPost', options);

export const runRobotUsingSvgApiV1RobotRunWithSvgPostOptions = (options: Options<RunRobotUsingSvgApiV1RobotRunWithSvgPostData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await runRobotUsingSvgApiV1RobotRunWithSvgPost({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: runRobotUsingSvgApiV1RobotRunWithSvgPostQueryKey(options)
    });
};

export const runRobotUsingSvgApiV1RobotRunWithSvgPostMutation = (options?: Partial<Options<RunRobotUsingSvgApiV1RobotRunWithSvgPostData>>) => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<RunRobotUsingSvgApiV1RobotRunWithSvgPostError>, Options<RunRobotUsingSvgApiV1RobotRunWithSvgPostData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await runRobotUsingSvgApiV1RobotRunWithSvgPost({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const runRobotUsingImageApiV1RobotRunWithImagePostQueryKey = (options: Options<RunRobotUsingImageApiV1RobotRunWithImagePostData>) => createQueryKey('runRobotUsingImageApiV1RobotRunWithImagePost', options);

export const runRobotUsingImageApiV1RobotRunWithImagePostOptions = (options: Options<RunRobotUsingImageApiV1RobotRunWithImagePostData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await runRobotUsingImageApiV1RobotRunWithImagePost({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: runRobotUsingImageApiV1RobotRunWithImagePostQueryKey(options)
    });
};

export const runRobotUsingImageApiV1RobotRunWithImagePostMutation = (options?: Partial<Options<RunRobotUsingImageApiV1RobotRunWithImagePostData>>) => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<RunRobotUsingImageApiV1RobotRunWithImagePostError>, Options<RunRobotUsingImageApiV1RobotRunWithImagePostData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await runRobotUsingImageApiV1RobotRunWithImagePost({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const summarizeTextApiV1GptsummarizePostQueryKey = (options: Options<SummarizeTextApiV1GptsummarizePostData>) => createQueryKey('summarizeTextApiV1GptsummarizePost', options);

export const summarizeTextApiV1GptsummarizePostOptions = (options: Options<SummarizeTextApiV1GptsummarizePostData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await summarizeTextApiV1GptsummarizePost({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: summarizeTextApiV1GptsummarizePostQueryKey(options)
    });
};

export const summarizeTextApiV1GptsummarizePostMutation = (options?: Partial<Options<SummarizeTextApiV1GptsummarizePostData>>) => {
    const mutationOptions: UseMutationOptions<SummarizeTextApiV1GptsummarizePostResponse, AxiosError<SummarizeTextApiV1GptsummarizePostError>, Options<SummarizeTextApiV1GptsummarizePostData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await summarizeTextApiV1GptsummarizePost({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};