// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, formDataBodySerializer } from '@hey-api/client-axios';
import type { ReturnListApiV1HealthTestListGetData, ReturnListApiV1HealthTestListGetResponse, ReturnListApiV1HealthTestListGetError, GenerateSvgFromPromptApiV1SvgGenerateSvgFromPromptPostData, GenerateSvgFromPromptApiV1SvgGenerateSvgFromPromptPostError, ConvertToSvgApiV1SvgConvertToSvgPostData, ConvertToSvgApiV1SvgConvertToSvgPostError, GetImageApiV1SvgImageImageNameGetData, GetImageApiV1SvgImageImageNameGetError, RunRobotUsingSvgApiV1RobotRunWithSvgPostData, RunRobotUsingSvgApiV1RobotRunWithSvgPostError, RunRobotUsingImageApiV1RobotRunWithImagePostData, RunRobotUsingImageApiV1RobotRunWithImagePostError, GetPreviewApiV1RobotGetPreviewPostData, GetPreviewApiV1RobotGetPreviewPostResponse, GetPreviewApiV1RobotGetPreviewPostError, GetControlApiV1RobotGetControlPostData, GetControlApiV1RobotGetControlPostResponse, GetControlApiV1RobotGetControlPostError, SummarizeTextApiV1GptsummarizePostData, SummarizeTextApiV1GptsummarizePostResponse, SummarizeTextApiV1GptsummarizePostError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Return List
 */
export const returnListApiV1HealthTestListGet = <ThrowOnError extends boolean = false>(options: Options<ReturnListApiV1HealthTestListGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ReturnListApiV1HealthTestListGetResponse, ReturnListApiV1HealthTestListGetError, ThrowOnError>({
        url: '/api/v1/health/test-list',
        ...options
    });
};

/**
 * Generate Svg From Prompt
 * API endpoint to generate SVG from a text prompt.
 */
export const generateSvgFromPromptApiV1SvgGenerateSvgFromPromptPost = <ThrowOnError extends boolean = false>(options: Options<GenerateSvgFromPromptApiV1SvgGenerateSvgFromPromptPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, GenerateSvgFromPromptApiV1SvgGenerateSvgFromPromptPostError, ThrowOnError>({
        url: '/api/v1/svg/generate_svg_from_prompt',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Convert To Svg
 * Convert an uploaded image to SVG and return its URL.
 */
export const convertToSvgApiV1SvgConvertToSvgPost = <ThrowOnError extends boolean = false>(options: Options<ConvertToSvgApiV1SvgConvertToSvgPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, ConvertToSvgApiV1SvgConvertToSvgPostError, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/api/v1/svg/convert_to_svg',
        ...options,
        headers: {
            'Content-Type': null,
            ...options?.headers
        }
    });
};

/**
 * Get Image
 * Retrieve a generated SVG image.
 */
export const getImageApiV1SvgImageImageNameGet = <ThrowOnError extends boolean = false>(options: Options<GetImageApiV1SvgImageImageNameGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<unknown, GetImageApiV1SvgImageImageNameGetError, ThrowOnError>({
        url: '/api/v1/svg/image/{image_name}',
        ...options
    });
};

/**
 * Run Robot Using Svg
 */
export const runRobotUsingSvgApiV1RobotRunWithSvgPost = <ThrowOnError extends boolean = false>(options: Options<RunRobotUsingSvgApiV1RobotRunWithSvgPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, RunRobotUsingSvgApiV1RobotRunWithSvgPostError, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/api/v1/robot/run_with_svg',
        ...options,
        headers: {
            'Content-Type': null,
            ...options?.headers
        }
    });
};

/**
 * Run Robot Using Image
 */
export const runRobotUsingImageApiV1RobotRunWithImagePost = <ThrowOnError extends boolean = false>(options: Options<RunRobotUsingImageApiV1RobotRunWithImagePostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, RunRobotUsingImageApiV1RobotRunWithImagePostError, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/api/v1/robot/run-with-image',
        ...options,
        headers: {
            'Content-Type': null,
            ...options?.headers
        }
    });
};

/**
 * Get Preview
 */
export const getPreviewApiV1RobotGetPreviewPost = <ThrowOnError extends boolean = false>(options: Options<GetPreviewApiV1RobotGetPreviewPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<GetPreviewApiV1RobotGetPreviewPostResponse, GetPreviewApiV1RobotGetPreviewPostError, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/api/v1/robot/get_preview',
        ...options,
        headers: {
            'Content-Type': null,
            ...options?.headers
        }
    });
};

/**
 * Get Control
 */
export const getControlApiV1RobotGetControlPost = <ThrowOnError extends boolean = false>(options: Options<GetControlApiV1RobotGetControlPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<GetControlApiV1RobotGetControlPostResponse, GetControlApiV1RobotGetControlPostError, ThrowOnError>({
        url: '/api/v1/robot/get_control',
        ...options
    });
};

/**
 * Summarize Text
 */
export const summarizeTextApiV1GptsummarizePost = <ThrowOnError extends boolean = false>(options: Options<SummarizeTextApiV1GptsummarizePostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<SummarizeTextApiV1GptsummarizePostResponse, SummarizeTextApiV1GptsummarizePostError, ThrowOnError>({
        url: '/api/v1/gptsummarize',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};