// This file is auto-generated by @hey-api/openapi-ts

export type BodyConvertToSvgApiV1SvgConvertToSvgPost = {
    /**
     * Image that should be converted to SVG.
     */
    img_file: Blob | File;
};

export type BodyGenerateSvgFromPromptApiV1SvgGenerateSvgFromPromptPost = {
    text: string;
};

export type BodyGetPreviewApiV1RobotGetPreviewPost = {
    /**
     * SVG file to upload for execution by robo simulation
     */
    svg_file: Blob | File;
};

export type BodyRunRobotUsingImageApiV1RobotRunWithImagePost = {
    /**
     * Image file that should be used by the robot to paint
     */
    img_file: Blob | File;
};

export type BodyRunRobotUsingSvgApiV1RobotRunWithSvgPost = {
    /**
     * SVG file that is used to run the model
     */
    svg_file: Blob | File;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type JsonExample = {
    text: string;
    type: string;
};

export type SumUpResponse = {
    text: string;
};

export type TextToSumUp = {
    text: string;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type ReturnListApiV1HealthTestListGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Auth token
         */
        token: string;
    };
    url: '/api/v1/health/test-list';
};

export type ReturnListApiV1HealthTestListGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReturnListApiV1HealthTestListGetError = ReturnListApiV1HealthTestListGetErrors[keyof ReturnListApiV1HealthTestListGetErrors];

export type ReturnListApiV1HealthTestListGetResponses = {
    /**
     * Successful Response
     */
    200: Array<JsonExample>;
};

export type ReturnListApiV1HealthTestListGetResponse = ReturnListApiV1HealthTestListGetResponses[keyof ReturnListApiV1HealthTestListGetResponses];

export type GenerateSvgFromPromptApiV1SvgGenerateSvgFromPromptPostData = {
    body: BodyGenerateSvgFromPromptApiV1SvgGenerateSvgFromPromptPost;
    path?: never;
    query: {
        /**
         * Auth token
         */
        token: string;
    };
    url: '/api/v1/svg/generate_svg_from_prompt';
};

export type GenerateSvgFromPromptApiV1SvgGenerateSvgFromPromptPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateSvgFromPromptApiV1SvgGenerateSvgFromPromptPostError = GenerateSvgFromPromptApiV1SvgGenerateSvgFromPromptPostErrors[keyof GenerateSvgFromPromptApiV1SvgGenerateSvgFromPromptPostErrors];

export type GenerateSvgFromPromptApiV1SvgGenerateSvgFromPromptPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ConvertToSvgApiV1SvgConvertToSvgPostData = {
    body: BodyConvertToSvgApiV1SvgConvertToSvgPost;
    path?: never;
    query: {
        /**
         * Auth token
         */
        token: string;
    };
    url: '/api/v1/svg/convert_to_svg';
};

export type ConvertToSvgApiV1SvgConvertToSvgPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConvertToSvgApiV1SvgConvertToSvgPostError = ConvertToSvgApiV1SvgConvertToSvgPostErrors[keyof ConvertToSvgApiV1SvgConvertToSvgPostErrors];

export type ConvertToSvgApiV1SvgConvertToSvgPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetImageApiV1SvgImageImageNameGetData = {
    body?: never;
    path: {
        image_name: string;
    };
    query: {
        /**
         * Auth token
         */
        token: string;
    };
    url: '/api/v1/svg/image/{image_name}';
};

export type GetImageApiV1SvgImageImageNameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetImageApiV1SvgImageImageNameGetError = GetImageApiV1SvgImageImageNameGetErrors[keyof GetImageApiV1SvgImageImageNameGetErrors];

export type GetImageApiV1SvgImageImageNameGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RunRobotUsingSvgApiV1RobotRunWithSvgPostData = {
    body: BodyRunRobotUsingSvgApiV1RobotRunWithSvgPost;
    path?: never;
    query: {
        /**
         * Auth token
         */
        token: string;
    };
    url: '/api/v1/robot/run_with_svg';
};

export type RunRobotUsingSvgApiV1RobotRunWithSvgPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunRobotUsingSvgApiV1RobotRunWithSvgPostError = RunRobotUsingSvgApiV1RobotRunWithSvgPostErrors[keyof RunRobotUsingSvgApiV1RobotRunWithSvgPostErrors];

export type RunRobotUsingSvgApiV1RobotRunWithSvgPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RunRobotUsingImageApiV1RobotRunWithImagePostData = {
    body: BodyRunRobotUsingImageApiV1RobotRunWithImagePost;
    path?: never;
    query: {
        /**
         * Auth token
         */
        token: string;
    };
    url: '/api/v1/robot/run-with-image';
};

export type RunRobotUsingImageApiV1RobotRunWithImagePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunRobotUsingImageApiV1RobotRunWithImagePostError = RunRobotUsingImageApiV1RobotRunWithImagePostErrors[keyof RunRobotUsingImageApiV1RobotRunWithImagePostErrors];

export type RunRobotUsingImageApiV1RobotRunWithImagePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPreviewApiV1RobotGetPreviewPostData = {
    body: BodyGetPreviewApiV1RobotGetPreviewPost;
    path?: never;
    query: {
        /**
         * Auth token
         */
        token: string;
    };
    url: '/api/v1/robot/get_preview';
};

export type GetPreviewApiV1RobotGetPreviewPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPreviewApiV1RobotGetPreviewPostError = GetPreviewApiV1RobotGetPreviewPostErrors[keyof GetPreviewApiV1RobotGetPreviewPostErrors];

export type GetPreviewApiV1RobotGetPreviewPostResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetPreviewApiV1RobotGetPreviewPostResponse = GetPreviewApiV1RobotGetPreviewPostResponses[keyof GetPreviewApiV1RobotGetPreviewPostResponses];

export type SummarizeTextApiV1GptsummarizePostData = {
    body: TextToSumUp;
    path?: never;
    query: {
        /**
         * Auth token
         */
        token: string;
    };
    url: '/api/v1/gptsummarize';
};

export type SummarizeTextApiV1GptsummarizePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SummarizeTextApiV1GptsummarizePostError = SummarizeTextApiV1GptsummarizePostErrors[keyof SummarizeTextApiV1GptsummarizePostErrors];

export type SummarizeTextApiV1GptsummarizePostResponses = {
    /**
     * Successful Response
     */
    200: SumUpResponse;
};

export type SummarizeTextApiV1GptsummarizePostResponse = SummarizeTextApiV1GptsummarizePostResponses[keyof SummarizeTextApiV1GptsummarizePostResponses];

export type ClientOptions = {
    baseURL: 'http://127.0.0.1:8000' | (string & {});
};